apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: envis-test
spec:
  environments:
    - name: dev
      build:
        from: test-performance
  components:
    - name: web
      publicPort: http
      dockerfileName: web/Dockerfile
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: '512Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '2000m'
          imageTagName: main-latest
  dnsAppAlias:
    environment: dev
    component: web
